name: Basic-Dispatch-Choice

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: false
        default: ''
        type: choice
        options:
          - MCGWS
          - MCSOS
          - ALL
          - ALLINV
          - ALLE2E

jobs:
  mcgws:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running input ${{ github.event.inputs.TEST_PROFILE }}"
  mcsos:
    runs-on: ubuntu-latest
    needs: mcgws
    steps:
      - run: echo "Running input ${{ github.event.inputs.TEST_PROFILE }}"