name: Basic-Dispatch

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: false
        default: ''

jobs:
  gwson:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running gwson using input ${{ github.event.inputs.TEST_PROFILE }}"