name: CFIT

on:
  schedule:
    # at minute 0 of every hour" i.e., runs once per hour, on the hour (00:00, 01:00, 02:00, ... 23:00)
    - cron: '0 8 * * *'
    - cron: '30 22 * * 4'
  workflow_dispatch:
    inputs:
      target:
        description: CFIT Test Suites
        required: true
        default: CFIT STAGING
        type: choice
        options:
          - CFIT STAGING
          - CFIT QA
    

env:
  EXPORT_TEMPLATE: RELEASE
  CF_RUNMODE: N

jobs:
  build:
    uses: ./.github/workflows/Compile.yml

  CFIT_App_Controls:
    if: > 
      (github.event_name == 'schedule' && 
       github.event.schedule == '0 8 * * *') || 
      (github.event_name == 'workflow_dispatch' && 
      (github.event.inputs.target == 'CFIT STAGING'))
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Maven
        env:
          EXPORT_TEMPLATE: ${{ env.EXPORT_TEMPLATE }}
          CF_RUNMODE: ${{ env.CF_RUNMODE }}
          POM_PROFILE: CFITAppControls
        run: bash .github/scripts/run-maven.sh

  CFIT_General:
    if: > 
      (github.event_name == 'schedule' && 
       github.event.schedule == '0 8 * * *') || 
      (github.event_name == 'workflow_dispatch' && 
      (github.event.inputs.target == 'CFIT STAGING'))
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Maven
        env:
          EXPORT_TEMPLATE: ${{ env.EXPORT_TEMPLATE }}
          CF_RUNMODE: ${{ env.CF_RUNMODE }}
          POM_PROFILE: CFITGeneral
        run: bash .github/scripts/run-maven.sh

    CFIT_QA:
    if: > 
      (github.event_name == 'schedule' && 
       github.event.schedule == '30 22 * * 4') || 
      (github.event_name == 'workflow_dispatch' && 
      (github.event.inputs.target == 'CFIT QA'))
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Maven
        env:
          EXPORT_TEMPLATE: 'TPV01'
          CF_RUNMODE: ${{ env.CF_RUNMODE }}
          POM_PROFILE: CFITQA
        run: bash .github/scripts/run-maven.sh
