name: CI Compile

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

jobs:
  compile:
    name: compile
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: Show versions
        shell: bash
        run: |
          java -version
          mvn -v
