name: Compile

on:
  pull_request:
  push:
    branches: ['**']
  workflow_dispatch:
  workflow_call:
      inputs:
        skip_build:
          required: false
          type: boolean
          default: false


jobs:
  compile:
    name: build
    if: ${{ !inputs.skip_build }}
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: Show versions
        shell: bash
        run: |
          java -version
      
      - name: Run Maven command
        run: mvn -version
        
      - name: Triggered by
        run: |
          echo "Triggered by ${{ github.actor }}"
