name: MC-ALL

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: true
        default: 'ALL'
        type: choice
        options:
          - MCGWS
          - MCGWSI
          - MCGWSE
          - MCGWSL

jobs:
  gws-all:
    uses: ./.github/workflows/MCGWS.yml
    
  sos-all:
    uses: ./.github/workflows/MCSOS.yml

