name: MC-ALL

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: true
        default: 'ALL'
        type: choice
        options:
          - MCGWS
          - MCGWSI
          - MCGWSE
          - MCGWSL

jobs:
  build:
    uses: ./.github/workflows/ci-compile.yml

  gwson:
    uses: ./.github/workflows/MCGWS.yml
    
  mcgwse:
    uses: ./.github/workflows/MCGWS.yml

  mcgwsi:
    uses: ./.github/workflows/MCGWS.yml

  mcgwsl:
   uses: ./.github/workflows/MCGWS.yml
