name: MC-ALL

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: false
        default: 'ALL'
        type: choice
        options:
          - ALL

jobs:
  gws-all:
    uses: ./.github/workflows/MCGWS.yml

  sos-all:
    needs: gws-all
    uses: ./.github/workflows/MCSOS.yml

