name: MCALL

on:
  schedule:
    # Example: Runs every day at midnight (Adjust as necessary)
    # GitHub Actions cron runs in UTC (Pacific Time is UTC-7) e.g. 0 9 * * * should run everynight at 2:00 AM PDT
    - cron: '0 16 * * *' 
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: true
        default: 'ALL'
        type: choice
        options: [ALL, ALLINV, ALLE2E]
      EXPORT_TEMPLATE:
        description: 'Export Template'
        required: false
        default: 'TPV01'
        type: string
      CF_RUNMODE:
        description: 'CFIT Runmode'
        required: false
        default: 'B'
        type: choice
        options: [A, B, N, P]

jobs:
  build:
    uses: ./.github/workflows/Compile.yml

  gws-all:
    needs: build
    uses: ./.github/workflows/MCGWS.yml
    with:
      TEST_PROFILE: ${{ inputs.TEST_PROFILE || 'ALL' }}
      EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE || 'TPV01' }}
      CF_RUNMODE: ${{ inputs.CF_RUNMODE || 'B' }}

  sos-all:
    needs: [build, gws-all]
    if: always()
    uses: ./.github/workflows/MCSOS.yml
    with:
      skip_build: true
      TEST_PROFILE: ${{ inputs.TEST_PROFILE || 'ALL' }}
      EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE || 'TPV01' }}
      CF_RUNMODE: ${{ inputs.CF_RUNMODE || 'B' }}
