name: MCGWS

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: true
        default: 'ALL'
        type: choice
        options: [MCGWS, MCGWSI, MCGWSE, MCGWSL]
      EXPORT_TEMPLATE:
        description: 'Export Template'
        required: false
        default: 'TPV01'
        type: string
      CF_RUNMODE:
        description: 'CFIT Runmode'
        required: false
        default: 'B'
        type: choice
        options: [A, B, N, P]
  workflow_call:
        inputs:
          skip_build:
            required: false
            type: boolean
            default: false         
          TEST_PROFILE:
            required: false
            type: string
            default: 'ALL'


jobs:
  build:
    if: ${{ !inputs.skip_build }}
    uses: ./.github/workflows/ci-compile.yml

  gwson:
    runs-on: ubuntu-latest
    needs: build
    # Evaluates the input directly. On schedule, inputs are blank, so the || 'ALL' defaults it to 'ALL'
    if: contains(fromJson('["MCGWS","MCGWSE","MCGWSI","MCGWSL","ALL"]'), inputs.TEST_PROFILE)  
    env:
      POM_PROFILE: GWS_ON
    steps:
      - name: Run Profile
        run: |
          echo "Turning GWS ON"
          echo "POM_PROFILE: $POM_PROFILE"
  # ================= PHASE 1 (PARALLEL) =================
  mcgwse:
    runs-on: ubuntu-latest
    needs: [build, gwson]
    # Evaluates the input directly. On schedule, inputs are blank, so the || 'ALL' defaults it to 'ALL'
    if: contains(fromJson('["MCGWS","MCGWSE","ALL"]'), inputs.TEST_PROFILE)
    env:
      POM_PROFILE: MCGWSE
    steps:
      - name: Run Profile
        run: |
          echo "TEST_PROFILE: ${{ inputs.TEST_PROFILE }}"
          echo "EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}"
          echo "CF_RUNMODE: ${{ inputs.CF_RUNMODE }}"
          echo "POM_PROFILE: $POM_PROFILE"
          
      - name: Run Maven
        run: bash .github/scripts/run-maven.sh


  mcgwsi:
    runs-on: ubuntu-latest
    needs: [build, gwson]
    if: contains(fromJson('["MCGWS","MCGWSI","ALL"]'), inputs.TEST_PROFILE)
    env:
      POM_PROFILE: MCGWSI
    steps:
      - name: Run Profile
        run: |
          echo "TEST_PROFILE: ${{ inputs.TEST_PROFILE }}"
          echo "EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}"
          echo "CF_RUNMODE: ${{ inputs.CF_RUNMODE }}"
          echo "POM_PROFILE: $POM_PROFILE"

  mcgwsl:
    runs-on: ubuntu-latest
    needs: [build, gwson]
    if: contains(fromJson('["MCGWS","MCGWSL","ALL"]'), inputs.TEST_PROFILE)
    env:
      POM_PROFILE: MCLite
    steps:
      - name: Run Profile
        run: |
          echo "TEST_PROFILE: ${{ inputs.TEST_PROFILE }}"
          echo "EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}"
          echo "CF_RUNMODE: ${{ inputs.CF_RUNMODE }}"
          echo "POM_PROFILE: $POM_PROFILE"
