name: MCGWS

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: true
        default: 'ALL'
        type: choice
        options: [MCGWS, MCGWSI, MCGWSE, MCGWSL]
      EXPORT_TEMPLATE:
        description: 'Export Template'
        required: false
        default: 'TPV01'
        type: string
      CF_RUNMODE:
        description: 'CFIT Runmode'
        required: false
        default: 'B'
        type: choice
        options: [A, B, N, P]
  workflow_call:
    inputs:
      skip_build:
        required: false
        type: boolean
        default: false
      TEST_PROFILE:
        required: false
        type: string
        default: 'ALL'
      EXPORT_TEMPLATE:
        required: false
        default: 'TPV01'
        type: string
      CF_RUNMODE:
        required: false
        default: 'B'
        type: string


jobs:
  # ================= PHASE 0 (BUILD) =================
  build:
    if: ${{ !inputs.skip_build }}
    uses: ./.github/workflows/ci-compile.yml

  # ================= PHASE 1 (GWS ON) =================
  gwson:
    runs-on: ubuntu-latest
    needs: build
    if: contains(fromJson('["MCGWS","MCGWSE","MCGWSI","MCGWSL","ALL", "ALLINV", "ALLE2E"]'), inputs.TEST_PROFILE)
    steps:
     - name: Run Maven profile
       uses: ./.github/actions/run-maven-profile
       with:
          POM_PROFILE: GWS_ON
          TEST_PROFILE: ${{ inputs.TEST_PROFILE }}
          EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}
          CF_RUNMODE: ${{ inputs.CF_RUNMODE }}

  # ================= PHASE 2 (PARALLEL: MCGWSE, MCGWSI, MCGWSL) =================
  mcgwse:
    runs-on: ubuntu-latest
    needs: [build, gwson]
    if: contains(fromJson('["MCGWS","MCGWSE","ALL", "ALLE2E"]'), inputs.TEST_PROFILE)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Maven
        env:
          TEST_PROFILE: ${{ inputs.TEST_PROFILE }}
          EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}
          CF_RUNMODE: ${{ inputs.CF_RUNMODE }}
          POM_PROFILE: MCGWSE
        run: bash .github/scripts/run-maven.sh

  mcgwsi:
    runs-on: ubuntu-latest
    needs: [build, gwson]
    if: contains(fromJson('["MCGWS","MCGWSI","ALL", "ALLINV"]'), inputs.TEST_PROFILE)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Maven
        env:
          TEST_PROFILE: ${{ inputs.TEST_PROFILE }}
          EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}
          CF_RUNMODE: ${{ inputs.CF_RUNMODE }}
          POM_PROFILE: MCGWSI
        run: bash .github/scripts/run-maven.sh

  mcgwsl:
    runs-on: ubuntu-latest
    needs: [build, gwson]
    if: contains(fromJson('["MCGWS","MCGWSL","ALL"]'), inputs.TEST_PROFILE)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run Maven
        env:
          TEST_PROFILE: ${{ inputs.TEST_PROFILE }}
          EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}
          CF_RUNMODE: ${{ inputs.CF_RUNMODE }}
          POM_PROFILE: MCGWSL
        run: bash .github/scripts/run-maven.sh
