name: MCSOS

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: true
        default: 'ALL'
        type: choice
        options: [MCSOS, MCSOSI, MCSOSE, MCSOSL]
      EXPORT_TEMPLATE:
        description: 'Export Template'
        required: false
        default: 'TPV01'
        type: string
      CF_RUNMODE:
        description: 'CFIT Runmode'
        required: false
        default: 'B'
        type: choice
        options: [A, B, N, P]
  workflow_call:
        inputs:
          skip_build:
            required: false
            type: boolean
            default: false
          TEST_PROFILE:
            required: false
            type: string
            default: 'ALL'


jobs:
  build:
    if: ${{ !inputs.skip_build }}
    uses: ./.github/workflows/ci-compile.yml

  soson:
    runs-on: ubuntu-latest
    needs: build
    # Evaluates the input directly. On schedule, inputs are blank, so the || 'ALL' defaults it to 'ALL'
    if: always() && contains(fromJson('["MCSOS","MCSOSE","MCSOSI","MCSOSL","ALL"]'), inputs.TEST_PROFILE) 
    steps:
      - name: Run Profile
        run: echo "Turning SOS ON"
  # ================= PHASE 1 (PARALLEL) =================
  mcsose:
    runs-on: ubuntu-latest
    needs: [build, soson]
    # Evaluates the input directly. On schedule, inputs are blank, so the || 'ALL' defaults it to 'ALL'
    if: always() && contains(fromJson('["MCSOS","MCSOSE","ALL"]'), inputs.TEST_PROFILE)
    steps:
      - name: Run Profile
        run: |
          echo "TEST_PROFILE: ${{ inputs.TEST_PROFILE }}"
          echo "EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}"
          echo "CF_RUNMODE: ${{ inputs.CF_RUNMODE }}"

  mcsosi:
    runs-on: ubuntu-latest
    needs: [build, soson]
    if: always() && contains(fromJson('["MCSOS","MCSOSI","ALL"]'), inputs.TEST_PROFILE)
    steps:
      - name: Run Profile
        run: |
          echo "TEST_PROFILE: ${{ inputs.TEST_PROFILE }}"
          echo "EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}"
          echo "CF_RUNMODE: ${{ inputs.CF_RUNMODE }}"

  mcsosl:
    runs-on: ubuntu-latest
    needs: [build, soson]
    if: always() && contains(fromJson('["MCSOS","MCSOSL","ALL"]'), inputs.TEST_PROFILE)
    steps:
      - name: Run Profile
        run: |
          echo "TEST_PROFILE: ${{ inputs.TEST_PROFILE }}"
          echo "EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}"
          echo "CF_RUNMODE: ${{ inputs.CF_RUNMODE }}"
