name: MCSOS

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: true
        default: 'ALL'
        type: choice
        options:
          - MCSOS
          - MCSOSI
          - MCSOSE
          - MCSOSL
          
  workflow_call:
        inputs:
          skip_build:
            required: false
            type: boolean
            default: false

jobs:
  build:
    if: ${{ !inputs.skip_build }}
    uses: ./.github/workflows/ci-compile.yml

  soson:
    runs-on: ubuntu-latest
    needs: build
    # Evaluates the input directly. On schedule, inputs are blank, so the || 'ALL' defaults it to 'ALL'
    if: | 
      always() &&
      (
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOS' || 
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOSE' ||
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOSI' ||
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOSL' ||
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'ALL'
      )
    steps:
      - name: Run Profile
        run: echo "Turning SOS ON"
  # ================= PHASE 1 (PARALLEL) =================
  mcsose:
    runs-on: ubuntu-latest
    needs: [build, soson]
    # Evaluates the input directly. On schedule, inputs are blank, so the || 'ALL' defaults it to 'ALL'
    if: |
      always() &&
      (
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOS' || 
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOSE' ||
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'ALL'
      )
    steps:
      - name: Run Profile
        run: echo "Running MCSOSE"

  mcsosi:
    runs-on: ubuntu-latest
    needs: [build, soson]
    if: |
      always() &&
      (
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOS' || 
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOSI' ||
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'ALL'
      )
    steps:
      - name: Run Profile
        run: echo "Running MCSOSI"

  mcsosl:
    runs-on: ubuntu-latest
    needs: [build, soson]
    if: |
      always() &&
      (
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOS' || 
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'MCSOSL' ||
        (github.event.inputs.TEST_PROFILE || 'ALL') == 'ALL'
      )
    steps:
      - name: Run Profile
        run: echo "Running MCSOSL"
