name: Run Maven Profile
description: Checkout repo and run Maven for a profile

inputs:
  POM_PROFILE:
    description: Maven profile to run
    required: true
  TEST_PROFILE:
    description: Test profile
    required: false
    default: ALL
  EXPORT_TEMPLATE:
    description: Export template
    required: false
    default: TPV01
  CF_RUNMODE:
    description: CFIT runmode
    required: false
    default: B

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Run Maven
      shell: bash
      env:
        TEST_PROFILE: ${{ inputs.TEST_PROFILE }}
        EXPORT_TEMPLATE: ${{ inputs.EXPORT_TEMPLATE }}
        CF_RUNMODE: ${{ inputs.CF_RUNMODE }}
        POM_PROFILE: ${{ inputs.POM_PROFILE }}
      run: bash .github/scripts/run-maven.sh